### ISSUE TITLE
Update from the old Vue CLI to Next.js + Flask

### ISSUE THREAD

**Issue by ghost** [skepfusky/pacopanda-drawing-stats#17]
bruh at this point you using ancient technology, but the vite dynamic img prop will be a problem tho, so i dunno

unless if I figured how to pass a img prop from a component, then yeah, I will migrate the project from there

## Todo
- [x]  make a FurAffinity and deviant web crawler in Python — pacopanda in FA, and pandapaco in DA
- [x]  use bs4 to scrape metadata and to jsonify it but only select of this month's range and not the whole goddamn thing
- [ ]  Run this script for 2 days consecutively
- [ ]  manually remove bits and pieces to be converted and parsed visually
- [ ]  finally update the database with new info
